# Generated by Django 5.2.3 on 2025-08-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecomparison',
            name='face_image',
            field=models.FileField(upload_to='face_images/faces/'),
        ),
        migrations.AlterField(
            model_name='facecomparison',
            name='passport_image',
            field=models.FileField(upload_to='face_images/passports/'),
        ),
    ]
