# Generated by Django 5.2.1 on 2025-06-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecomparison',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='face_comparisons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
