# Generated by Django 5.2.3 on 2025-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facecomparison_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='gmail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profil/image'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
