# Generated by Django 5.2.3 on 2025-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_facecomparison_face_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecomparison',
            name='face_image',
            field=models.ImageField(upload_to='face_images/faces/'),
        ),
        migrations.AlterField(
            model_name='facecomparison',
            name='passport_image',
            field=models.ImageField(upload_to='face_images/passports/'),
        ),
    ]
