# Generated by Django 5.2.3 on 2025-06-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_abstractuser_gmail_abstractuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='gmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
