# Generated by Django 5.2.3 on 2025-06-18 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_abstractuser_gmail_alter_abstractuser_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='telegram',
        ),
        migrations.CreateModel(
            name='Userprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gmail', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
