version: '3.9'

services:
  web:
    build: .
    container_name: ijara_backend-web
    ports:
      - "8022:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=faceid
      - DJANGO_DB_USER=faceid_user
      - DJANGO_DB_PASSWORD=faceid_pass

  db:
    image: postgres:15
    container_name: ijara_backend-db
    environment:
      POSTGRES_DB: faceid
      POSTGRES_USER: faceid_user
      POSTGRES_PASSWORD: faceid_pass
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: ijara_backend-redis
    ports:
      - "6380:6379"

volumes:
  postgres_data:
