version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    command: >
      sh -c "/Fac/.venv/bin/python manage.py migrate &&
             /Fac/.venv/bin/python manage.py collectstatic --noinput &&
             /Fac/.venv/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3 --threads=2 --timeout=120"
    volumes:
      - .:/Fac
      - static_volume:/Fac/staticfiles
      - media_volume:/Fac/mediafiles
    ports:
      - "8022:8000"
    depends_on:
      - faceid_db
      - redis
    restart: always

  faceid_db:
    image: postgis/postgis:latest
    container_name: faceid_db
    environment:
      POSTGRES_DB: faceid
      POSTGRES_USER: user_faceid
      POSTGRES_PASSWORD: password_faceid
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_faceid -d faceid"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
