version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/Faceid
      - static_volume:/Faceid/staticfiles
      - media_volume:/Faceid/mediafiles
    ports:
      - "8022:8000"
    depends_on:
      - faceid_db
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    restart: always

  faceid_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: faceid
      POSTGRES_USER: user_faceid
      POSTGRES_PASSWORD: password_faceid
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
