
version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Fac
      - static_volume:/Fac/staticfiles
      - media_volume:/Fac/mediafiles
    ports:
      - "8022:8000"
    depends_on:
      - fac_db
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  fac_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fac
      POSTGRES_USER: user_fac
      POSTGRES_PASSWORD: password_fac
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:







#version: '3.9'
#
#services:
#  web:
#    build: .
#    container_name: ijara_backend-web
#    ports:
#      - "8022:8000"
#    depends_on:
#      - db
#      - redis
#    environment:
#      - DEBUG=1
#      - DJANGO_DB_HOST=db
#      - DJANGO_DB_PORT=5432
#      - DJANGO_DB_NAME=faceid
#      - DJANGO_DB_USER=faceid_user
#      - DJANGO_DB_PASSWORD=faceid_pass
#
#  db:
#    image: postgres:15
#    container_name: ijara_backend-db
#    environment:
#      POSTGRES_DB: faceid
#      POSTGRES_USER: faceid_user
#      POSTGRES_PASSWORD: faceid_pass
#    ports:
#      - "5440:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  redis:
#    image: redis:alpine
#    container_name: ijara_backend-redis
#    ports:
#      - "6380:6379"
#
#volumes:
#  postgres_data:
