# Generated by Django 5.2.3 on 2025-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('deactive', 'NoFaol')], default='pending', max_length=10),
        ),
    ]
