# Generated by Django 5.2.3 on 2025-06-23 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_district_region_remove_house_address_house_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
