# Generated by Django 5.2.3 on 2025-06-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
    ]
