# Generated by Django 5.2.3 on 2025-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_alter_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
