# Generated by Django 5.2.5 on 2025-09-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
